### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by niizam** [libredeb/slingscold#4]
how to uninstall slingscold ?
i want to use lightpad instead

**Comment by libredeb** [comment]
Hi, sorry for this inconvenient. You have the option to remove the files manually.

**Run this command in a terminal (without copy the $):**
```
$ rm -Rf /usr/share/applications/slingscold.desktop /usr/share/icons/hicolor/32x32/apps/slingscold.svg /usr/share/icons/hicolor/48x48/apps/slingscold.svg /usr/share/icons/hicolor/64x64/apps/slingscold.svg /usr/share/icons/hicolor/128x128/apps/slingscold.svg /usr/bin/slingscold
```
And then follow the instructions in the **Compilation** section of the LightPad project: https://github.com/libredeb/lightpad

Regards!
