### ISSUE TITLE
sometimes it doesn't work

### ISSUE THREAD

**Issue by zayronxio** [libredeb/slingscold#5]
sometimes slingscold does not work, I tried it from terminal every certain period of attempts throws this bug messenge 

ERROR:arraylist.c:1181:gee_array_list_real_get: assertion failed: (index >= 0)
Bail out! ERROR:arraylist.c:1181:gee_array_list_real_get: assertion failed: (index >= 0)
Abortado (`core' generado)

**Comment by libredeb** [comment]
Hi @zayronxio **Slingscold** has no more support anymore. The project has evolve to the [Lightpad](https://github.com/libredeb/lightpad) project.

Regards!
